version: 2.1
orbs:
  tools: entur/tools@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5

filters: &filters
  tags:
    only: /.*/

jobs:
  test-run-commands:
    executor: tools/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker
      - tools/shorten-branch-name
      - tools/create-entur-tag
      - tools/create-docker-image

workflows:
  test-deploy:
    jobs:
      - test-run-commands:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          name: Publish (production) Orb which cannot be deleted
          orb-name: entur/tools
          vcs-type: << pipeline.project.type >>
          pub-type: production
          enable-pr-comment: false
          requires:
            - orb-tools/pack
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

# VS Code Extension Version: 1.4.0
