description: >
  This is a executor using the Google Cloud SDK Docker image. It is a wrapper for the Google Cloud SDK and allows the the user to run `gcloud` commands
docker:
  - image: 'google/cloud-sdk'
parameters:
  tag:
    default: alpine
    description: >
      Pick a specific google/cloud-sdk image variant:
      https://hub.docker.com/r/google/cloud-sdk/tags
    type: string
